
def obter_diretorios():
    print("#### <ENTROU EM obter_diretorios (em caminho_dados.py)> ####\n")

    DIRETORIO_CLIENTES_ARMAZENAMENTO = "DIRETORIO_CLIENTES"
    ARQUIVO_DADOS_CLIENTES = "dados_clientes.json"

    print(f"DIRETORIO_CLIENTES_ARMAZENAMENTO: {DIRETORIO_CLIENTES_ARMAZENAMENTO}\nARQUIVO_DADOS_CLIENTES: {ARQUIVO_DADOS_CLIENTES}\n")

    return DIRETORIO_CLIENTES_ARMAZENAMENTO, ARQUIVO_DADOS_CLIENTES